# Generated by Django 6.0.1 on 2026-01-16 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=100)),
                ('nicknames', models.CharField(blank=True, help_text='Comma-separated nicknames', max_length=255)),
                ('identifying_characteristics', models.TextField()),
                ('preferred_baits_lures', models.TextField(help_text='Preferred baits and lures')),
                ('best_fishing_method', models.CharField(max_length=100)),
                ('preferred_environments', models.CharField(help_text='Comma-separated environments', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm or inches', max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg or lbs', max_digits=6)),
                ('catch_location', models.CharField(max_length=255)),
                ('catch_datetime', models.DateTimeField()),
                ('weather_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('released', models.BooleanField(default=True, help_text='Released (True) or kept (False)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to=settings.AUTH_USER_MODEL)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='angler.fish')),
            ],
        ),
    ]
