# Generated by Django 6.0.1 on 2026-01-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'verbose_name': 'Catch', 'verbose_name_plural': 'Catches'},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name': 'Fish Species', 'verbose_name_plural': 'Fish Species'},
        ),
        migrations.AddField(
            model_name='catch',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', max_length=2),
        ),
        migrations.AddField(
            model_name='catch',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', max_length=3),
        ),
        migrations.AlterField(
            model_name='catch',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Length value', max_digits=6),
        ),
        migrations.AlterField(
            model_name='catch',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight value', max_digits=6),
        ),
    ]
