# Generated by Django 6.0.1 on 2026-01-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0002_alter_catch_options_alter_fish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the catch', null=True, upload_to='catch_photos/'),
        ),
    ]
