# Generated by Django 6.0.1 on 2026-01-25 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0003_catch_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='bait',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='catch',
            name='lure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FishingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('weather_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fishing Session',
                'verbose_name_plural': 'Fishing Sessions',
            },
        ),
        migrations.AddField(
            model_name='catch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='angler.fishingsession'),
        ),
    ]
