# Generated by Django 6.0.1 on 2026-01-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0004_catch_bait_catch_lure_fishingsession_catch_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingsession',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
