# Generated by Django 6.0.1 on 2026-01-27 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0005_alter_fishingsession_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
