# Generated by Django 6.0.1 on 2026-01-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0006_fishingsession_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='session',
            new_name='session_id',
        ),
    ]
