# Generated by Django 6.0.1 on 2026-01-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler', '0007_rename_session_catch_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='session_id',
            new_name='session',
        ),
    ]
